#!/usr/bin/env bash
FolderPath="$HOME/Documents/AndroidScreenshots"
if [ ! -d "$FolderPath" ]; then
mkdir $FolderPath;
fi

chmod 777 $FolderPath;

adb devices|tail -n +2|cut -f -1|sed '$d'|
while read line 
do 
modno=$(adb -s $line shell getprop ro.product.model)
	echo "Capturing screenshot from ${modno}"
	
	adb -s $line shell screencap /sdcard/screenshot.png
timeStamp=$(date '+%Y_%m_%d_%H_%M_%S');
#modelno= adb devices|tail -n +2|cut -f -1|sed '$d'|while read line; do adb -s $line shell getprop ro.product.model; done
fileName="${timeStamp}_${modno}.png";
 
 echo "$fileName"

adb -s $line pull /sdcard/screenshot.png $FolderPath'/'$fileName
adb -s $line shell rm /sdcard/screenshot.png
done
